//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DVLAEntities : DbContext
    {
        public DVLAEntities()
            : base("name=DVLAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Colour> Colours { get; set; }
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Camera> Cameras { get; set; }
        public virtual DbSet<SpeedCamera> SpeedCameras { get; set; }
        public virtual DbSet<TrafficLightCamera> TrafficLightCameras { get; set; }
        public virtual DbSet<Fine> Fines { get; set; }
        public virtual DbSet<Sighting> Sightings { get; set; }
    }
}
